# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='transactions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
