# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20161020_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
