# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
